import { z } from 'zod';
import { defineContract } from '../core/tool_contract.js';
import { Vector3Schema } from '../domain/primitives.schema.js';

// ─── Ministry Evaluation ─────────────────────────────────────────────────────

export const DesiredStateSchema = z.object({
    objectiveId: z.string().describe("Target objective ID"),
    targetPosition: Vector3Schema.describe("Strategic target coordinate"),
    priority: z.number().min(0).max(100).describe("Objective priority"),
    resourceNeeds: z.array(z.string()).describe("List of unit types required")
}).describe("Ministry's generated strategic evaluation");

// ─── ministry_get_evaluation ─────────────────────────────────────────────────

export const MinistryGetEvaluationInputSchema = z.object({
    matchId: z.string().describe("The match ID"),
    side: z.string().describe("Side to evaluate")
});

export const ministryGetEvaluationContract = defineContract({
    domain: 'ministry',
    action: 'get_evaluation',
    description: 'Retrieve the DesiredState generated by an AI Ministry.',
    inputSchema: MinistryGetEvaluationInputSchema,
    outputSchema: DesiredStateSchema,
    rest: { method: 'GET', path: '/matches/:matchId/ministries/:side/evaluation' }
});

// ─── ministry_update_doctrine ────────────────────────────────────────────────

export const MinistryUpdateDoctrineInputSchema = z.object({
    matchId: z.string().describe("The match ID"),
    side: z.string().describe("Side to update"),
    aggressiveness: z.number().min(0).max(1).optional().describe("0 (defensive) to 1 (aggressive)"),
    riskTolerance: z.number().min(0).max(1).optional().describe("Risk limit for high-value assets")
});

export const MinistryUpdateDoctrineOutputSchema = z.object({ 
    success: z.boolean().describe("Whether doctrine was updated")
});

export const ministryUpdateDoctrineContract = defineContract({
    domain: 'ministry',
    action: 'update_doctrine',
    description: 'Inject doctrine parameters to change Ministry behavior.',
    inputSchema: MinistryUpdateDoctrineInputSchema,
    outputSchema: MinistryUpdateDoctrineOutputSchema,
    rest: { method: 'PATCH', path: '/matches/:matchId/ministries/:side/doctrine' }
});
