import { z } from 'zod';
import { defineContract } from '../core/tool_contract.js';
import { MissionSchema, MissionTypeSchema, MissionStatusSchema, MissionParamsSchema } from '../domain/tactical.schema.js';

// ─── mission_list ────────────────────────────────────────────────────────────

export const MissionListInputSchema = z.object({
    matchId: z.string().describe("The match ID"),
    entityId: z.string().describe("The entity ID")
});

export const MissionListOutputSchema = z.object({
    missions: z.array(MissionSchema).describe("Active and queued missions")
});

export const missionListContract = defineContract({
    domain: 'mission',
    action: 'list',
    description: 'List all active and queued missions for a unit.',
    inputSchema: MissionListInputSchema,
    outputSchema: MissionListOutputSchema,
    rest: { method: 'GET', path: '/matches/:matchId/entities/:entityId/missions' }
});

// ─── mission_create ──────────────────────────────────────────────────────────

export const MissionCreateInputSchema = z.object({
    matchId: z.string().describe("The match ID"),
    entityId: z.string().describe("The entity ID"),
    missionType: MissionTypeSchema.describe("Mission objective type"),
    params: MissionParamsSchema.optional().describe("Mission parameters")
});

export const missionCreateContract = defineContract({
    domain: 'mission',
    action: 'create',
    description: 'Assign a new mission to a unit.',
    inputSchema: MissionCreateInputSchema,
    outputSchema: MissionSchema,
    rest: { method: 'POST', path: '/matches/:matchId/entities/:entityId/missions' }
});

// ─── mission_get_tasks ───────────────────────────────────────────────────────

export const TaskSummarySchema = z.object({
    id: z.string().describe("Task ID"),
    type: z.string().describe("Task type"),
    status: z.string().describe("Task execution status"),
    dependencies: z.array(z.string()).describe("IDs of prerequisite tasks")
}).describe("Summary of a low-level task");

export const MissionGetTasksInputSchema = z.object({
    matchId: z.string().describe("The match ID"),
    entityId: z.string().describe("The entity ID")
});

export const MissionGetTasksOutputSchema = z.object({
    tasks: z.array(TaskSummarySchema).describe("Generated tasks")
});

export const missionGetTasksContract = defineContract({
    domain: 'mission',
    action: 'get_tasks',
    description: 'Inspect low-level tasks generated by the mission system.',
    inputSchema: MissionGetTasksInputSchema,
    outputSchema: MissionGetTasksOutputSchema,
    rest: { method: 'GET', path: '/matches/:matchId/entities/:entityId/tasks' }
});
